stages:
    - tests
    - deploy

php-cs-fixer:
    image: php:7.2
    stage: tests
    script:
        - php php-cs-fixer fix --dry-run --using-cache=no .

deploy:
    image: mwienk/docker-lftp
    stage: deploy
    environment: production
    when: on_success
    only:
        - master
    script:
        - lftp -e "set ftp:ssl-allow no; open esgi-iw.fr; user $FTP_USERNAME $FTP_PASSWORD; mirror --reverse --verbose ./ .; bye"
